<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (!class_exists(\ContainerPyypxpo\appProdProjectContainer::class, false)) {
    require __DIR__.'/ContainerPyypxpo/appProdProjectContainer.php';
}

if (!class_exists(appProdProjectContainer::class, false)) {
    class_alias(\ContainerPyypxpo\appProdProjectContainer::class, appProdProjectContainer::class, false);
}

return new \ContainerPyypxpo\appProdProjectContainer();
