<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (!class_exists(\ContainerBgaavsk\appDevDebugProjectContainer::class, false)) {
    require __DIR__.'/ContainerBgaavsk/appDevDebugProjectContainer.php';
}

if (!class_exists(appDevDebugProjectContainer::class, false)) {
    class_alias(\ContainerBgaavsk\appDevDebugProjectContainer::class, appDevDebugProjectContainer::class, false);
}

return new \ContainerBgaavsk\appDevDebugProjectContainer();
